# Generated by Django 6.1.1 on 2026-09-06 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('p_type', models.CharField(choices=[('FULL_ACCESS', 'Full Access'), ('FULL_DENIED', 'Full Denied'), ('SEMI_ACCESS', 'Semi Access'), ('SEMI_DENIED', 'Semi Denied')], default='FULL_DENIED', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('p_type', models.CharField(choices=[('ACCESS', 'Access'), ('DENIED', 'Denied')], max_length=100)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_api.country')),
            ],
        ),
    ]
