# Generated by Django 6.1.1 on 2026-09-06 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_api', '0002_rename_models_and_add_indexes'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='country',
            table='test_api_country',
        ),
        migrations.AlterModelTable(
            name='iprecord',
            table='test_api_ips',
        ),
    ]
